name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: npm install
        run: npm install

      - name: gatsby build
        run: npm build

      - name: deploy
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.BLOG_TOKEN }}