# name: Gatsby Publish

# on:
#   push:
#     branches:
#       - dev

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1

#       - name: Setup Node
#         uses: actions/setup-node@v1
#         with:
#           node-version: '14.x'

#       - name: Cache node_modules
#         uses: actions/cache@v1
#         width:
#           path: node_modules
#           key: ${{runner.OS}}-build-${{hashFiles('**/yarn.lock')}}
#           restore-keys: |
#             ${{ runner.OS }}-build-${{ runner.OS }}-

#       - name: npm install
#         run: npm install

#       - name: gatsby build
#         run: npm build

#       - name: deploy
#         uses: enriikke/gatsby-gh-pages-action@v2
#         with:
#           access-token: ${{ secrets.BLOG_TOKEN }}

name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages